# Generated by Django 5.0.3 on 2024-03-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_leave_isapproved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='isApproved',
            new_name='status',
        ),
    ]
