# Generated by Django 5.0.3 on 2024-03-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_employee_password_alter_leave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
